spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forest_game
    username: forest_game_api
    password: wOfVY62QHSPC6hMvbou2
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop
logging:
  path: log/
  level:
    com.nodemules.games.forest: trace
  pattern:
    console:
