INSERT INTO ITEM (NAME, DESCRIPTION)
VALUES ('TOAST', 'A slice of toast');
INSERT INTO ITEM (NAME, DESCRIPTION)
VALUES ('ROAST', 'A slice of roast');

INSERT INTO USER (USERNAME)
VALUES ('LIAM_NEESON');
INSERT INTO USER (USERNAME, PASSWORD)
VALUES ('TEST_USERNAME', '$2a$10$no8cdDkoISG5gV8KkuU77OqW/L2qjScLdxtv6yTuFdcwEZKOzN2My');